language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - python -m pytest
after_success: |
  if [[ "$TRAVIS_BRANCH" != "master" ]]; then
    pip install twine
    python setup.py sdist bdist_wheel
    twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u kai25 -p $PYPI_PASSWORD
  fi