language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - echo OK
after_success:
  - pip install twine
  - python setup.py sdist bdist_wheel
  - twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u kai25 -p $PYPI_PASSWORD