---
version: 2
jobs:
  test:
    working_directory: /opt/build
    docker:
      - image: python:3.7.1-alpine3.8
    steps:
      - run:
          name: Install system dependencies
          command: apk add -U git openssh curl tar
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirements.txt
            pip3 install -r requirements-test.txt
      - run:
          name: Install Allure
          command: |
            mkdir -p /tmp/allure
            curl -L -o /tmp/allure.tgz https://github.com/allure-framework/allure2/releases/download/2.7.0/allure-2.7.0.tgz
            tar -zxf /tmp/allure.tgz --strip-components=1 -C /tmp/allure
            chmod +x /tmp/allure/bin/allure
            ln -s /tmp/allure/bin/allure /usr/local/bin/allure
      - run:
          name: Run tests
          command: |
            python -m pytest --allure-dir=/tmp/allure-tests --junitxml=/tmp/junit.xml
            allure generate -o /tmp/allure-reports /tmp/allure-tests
      - store_artifacts:
          path: "/tmp/allure-reports"
          destination: allure
      - store_test_results:
          path: "/tmp/junit.xml"
      - run:
          name: Push to PyPi
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              pip install twine
              python setup.py sdist bdist_wheel
              twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
            fi
workflows:
  version: 2
  test_and_docker:
    jobs:
      - test
      - docker:
          context: org-global
          requires:
            - test
          filters:
            tags:
              only: /.*/
